@startuml
skinparam classAttributeIconSize 0
class Typkonvertierungen{
 +main() static
 -convertByte(byte : _byte) static
 -convertShort(short : _short) static
 -convertInt(int : _int) static
 -convertLong(long : _long) static
 -convertChar(char : _char) static
 -convertFloat(float : _float) static
 -convertDouble(double : _double) static
}
@enduml
