@startuml
skinparam classAttributeIconSize 0
class Operatoren{
 +main() static
 -arithmetisch() static
 -inkrement() static
 -vergleiche() static
 -boolische() static
 -bitshifting() static
 -zuweisung() static
}
@enduml
